spring:
  cloud:
    # openFeign 配置
    openfeign:
      client:
        config:
          default:
            read-timeout: 3000  # 默认读取时间
            connect-timeout: 3000 # 默认连接时间
  config:
    import:
      - nacos:druid-common.yaml?group=test&refreshEnable=true
      - nacos:redis-common.yaml?group=test&refreshEnable=true
      - nacos:application-dev.yaml?group=test&refreshEnable=true # spring 静态资源路径配置，mybatis配置
    activate:
      on-profile: test # 动态激活判断，如果当前是 dev 环境才会生效