server:
  port: 9001
spring:
  profiles:
    active: dev
  main:
    lazy-initialization: true # 开启懒加载
  application:
    name: user-customer
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848 # nacos 服务地址和端口号
      config:
        import-check:
          enabled: false # 关闭检查
        namespace: dev
      discovery:
        namespace: dev
    # sentinel 配置
    sentinel:
      transport:
        dashboard: localhost:8080 # sentinel 监控页面
      datasource: # 配置限流
        ds1:
          nacos:
            server-addr: localhost:8848
            data-id: user_customer_sentinel
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: flow # 流控规则
      eager: true # sentinel 进行提前加载，不然访问不到 sentinel
    # openFeign 配置
    openfeign:
      client:
        config:
          default:
            read-timeout: 3000  # 默认读取时间
            connect-timeout: 3000 # 默认连接时间
# 开启熔断功能
feign:
  sentinel:
    enabled: true

gateway-url: http://localhost:80/${spring.application.name}