server:
  port: 80
spring:
# 配置静态资源路径
  web:
    resources:
      static-locations: "file:../Music/static/"
  webflux:
    static-path-pattern: /static/**
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848
      config:
        namespace: dev
      discovery:
        namespace: dev
    gateway:
      discovery:
        locator:
          # 根据注册中心的服务自动生成路由
          enabled: true
          # 路由名转小写
          lower-case-service-id: true
      # 解决跨域问题
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
        # 解决options请求被拦截的问题
        add-to-simple-url-handler-mapping: true
      routes:
        - id: music-customer
          uri: lb://music-customer # 音乐模块
          predicates:
            - Path=/api/music/**
          order: 0 # 优先级最高
        - id: user-customer
          uri: lb://user-customer # 用户模块
          predicates:
            - Path=/api/user/**
          order: 0